# Specify the database path
DATABASE_PATH = "data/listings.sqlite"

# Specify the cities list
# Note: If this list is not specified, all cities in the data/usa folder will be used
CITIES = []

AIRBNB_COLORS = {
    "main": "#FF5A5F",  # Rausch
    "green": "#00A699",  # Babu
    "orange": "#FC642D",  # Arches
    "darkgrey": "#484848",  # Hof
    "lightgrey": "#767676",  # Foggy
}

BENS_COLORS = {
    "nature-green": "#236F21",
    "tiffany-blue": "#83C5BE",
    "alice-blue": "#EDF6F9",
    "pale-dogwood": "#FFDDD2",
    "charcoal": "#2E5266",
}

# Mapping official Airbnb categories
AMENITY_CATEGORIES = {
    "Popular": [
        "Essentials",
        "Air conditioning",
        "Cleaning products",
        "Cooking basics",
        "Dedicated workspace",
        "Dishes and silverware",
        "Dryer",
        "Hair dryer",
        "Heating",
        "Hot tub",
        "Kitchen",
        "Pool",
        "TV",
        "Washer",
        "Wifi",
    ],
    "Bathroom": [
        "Bathtub",
        "Bidet",
        "Body soap",
        "Cleaning products",
        "Conditioner",
        "Hair dryer",
        "Hot water",
        "Outdoor shower",
        "Shampoo",
        "Shower gel",
    ],
    "Bedroom and laundry": [
        "Essentials",
        "Bed linens",
        "Clothing storage",
        "Dryer",
        "Drying rack for clothing",
        "Extra pillows and blankets",
        "Hangers",
        "Iron",
        "Mosquito net",
        "Room-darkening shades",
        "Safe",
        "Washer",
    ],
    "Entertainment": [
        "Arcade games",
        "Batting cage",
        "Books and reading material",
        "Bowling alley",
        "Climbing wall",
        "Ethernet connection",
        "Exercise equipment",
        "Game console",
        "Laser tag",
        "Life size games",
        "Mini golf",
        "Movie theater",
        "Piano",
        "Ping pong table",
        "Pool table",
        "Record player",
        "Skate ramp",
        "Sound system",
        "Theme room",
        "TV",
    ],
    "Family": [
        "Baby bath",
        "Baby monitor",
        "Children’s bikes",
        "Children's playroom",
        "Baby safety gates",
        "Babysitter recommendations",
        "Board games",
        "Changing table",
        "Children’s books and toys",
        "Children’s dinnerware",
        "Crib",
        "Fireplace guards",
        "High chair",
        "Outdoor playground",
        "Outlet covers",
        "Pack ’n play/Travel crib",
        "Table corner guards",
        "Window guards",
    ],
    "Heating and cooling": [
        "Air conditioning",
        "Ceiling fan",
        "Heating",
        "Indoor fireplace",
        "Portable fans",
    ],
    "Home safety": [
        "Carbon monoxide alarm",
        "Fire extinguisher",
        "First aid kit",
        "Smoke alarm",
    ],
    "Internet and office": ["Dedicated workspace", "Pocket wifi", "Wifi"],
    "Kitchen and dining": [
        "Barbecue utensils",
        "Bread maker",
        "Blender",
        "Coffee",
        "Coffee maker",
        "Cooking basics",
        "Dining table",
        "Dishes and silverware",
        "Dishwasher",
        "Freezer",
        "Hot water kettle",
    ],
    "Kitchen": [
        "Kitchenette",
        "Microwave",
        "Mini fridge",
        "Oven",
        "Refrigerator",
        "Rice maker",
        "Stove",
        "Toaster",
        "Trash compactor",
        "Wine glasses",
    ],
    "Location features": [
        "Beach access",
        "Lake access",
        "Laundromat nearby",
        "Private entrance",
        "Resort access",
        "Ski-in/Ski-out",
        "Waterfront",
    ],
    "Outdoor": [
        "Backyard",
        "BBQ grill",
        "Beach essentials",
        "Bikes",
        "Boat slip",
        "Fire pit",
        "Hammock",
        "Kayak",
        "Outdoor dining area",
        "Outdoor furniture",
        "Outdoor kitchen",
        "Patio or balcony",
        "Sun loungers",
    ],
    "Parking and facilities": [
        "Elevator",
        "EV charger",
        "Free parking on premises",
        "Hockey rink",
        "Free street parking",
        "Gym",
        "Hot tub",
        "Public or shared",
        "Paid parking off premises",
        "Paid parking on premises",
        "Pool",
        "Private living room",
        "Sauna",
        "Single level home",
    ],
    "Services": [
        "Breakfast",
        "Cleaning available during stay",
        "Long term stays allowed",
        "Luggage dropoff allowed",
    ],
}


# Set the types of columns for reading from CSV using pandas
COLUMN_IMPORT_TYPES = {
    "id": "int64",
    "listing_url": "str",
    "scrape_id": "float32",
    "last_scraped": "str",
    "scrape_name": "str",
    "name": "str",
    "description": "str",
    "picture_url": "str",
    "host_id": "float32",
    "host_url": "str",
    "host_name": "str",
    "host_since": "str",
    "host_location": "str",
    "host_about": "str",
    "host_response_time": "str",
    "host_response_rate": "str",
    "host_acceptance_rate": "str",
    "host_is_superhost": "str",
    "host_thumbnail_url": "str",
    "host_picture_url": "str",
    "host_neighbourhood": "str",
    "host_listings_count": "float32",
    "host_total_listings_count": "float32",
    "host_verifications": "str",
    "host_has_profile_pic": "str",
    "host_identity_verified": "str",
    "neighbourhood": "str",
    "neighbourhood_cleansed": "str",
    "latitude": "float32",
    "longitude": "float32",
    "property_type": "str",
    "room_type": "str",
    "accommodates": "float32",
    "bathrooms": "float32",
    "bathroom_text": "str",
    "bedrooms": "float32",
    "amenities": "str",
    "price": "str",
    "minimum_nights": "float32",
    "maximum_nights": "float32",
    "minimum_minimum_nights": "float32",
    "maximum_minimum_nights": "float32",
    "minimum_maximum_nights": "float32",
    "maximum_maximum_nights": "float32",
    "minimum_nights_avg_ntm": "float32",
    "maximum_nights_avg_ntm": "float32",
    "has_availability": "str",
    "availability_30": "float32",
    "availability_60": "float32",
    "availability_90": "float32",
    "availability_365": "float32",
    "calendar_last_scraped": "str",
    "number_of_reviews": "float32",
    "number_of_reviews_ltm": "float32",
    "first_review": "str",
    "last_review": "str",
    "review_scores_rating": "float64",
    "review_scores_accuracy": "float64",
    "review_scores_cleanliness": "float64",
    "review_scores_checkin": "float64",
    "review_scores_communication": "float64",
    "review_scores_location": "float64",
    "review_scores_value": "float64",
    "license": "str",
    "instant_bookable": "str",
    "reviews_per_month": "float32",
    "calculated_host_listings_count": "float32",
    "calculated_host_listings_count_entire_homes": "float32",
    "calculated_host_listings_count_private_rooms": "float32",
    "calculated_host_listings_count_shared_rooms": "float32",
}

# Specify the columns that need to be rounded as part of the review scores table
REVIEW_SCORES_COLUMNS = [
    "review_scores_rating",
    "review_scores_accuracy",
    "review_scores_cleanliness",
    "review_scores_checkin",
    "review_scores_communication",
    "review_scores_location",
    "review_scores_value",
]

AMENITY_WHITELIST = [
    "body soap",
    "conditioner",
    "shampoo",
    "sound system",
    "refrigerator",
    "wifi",
    "stove",
    "steel oven",
    "hdtv",
    "oven",
    "tv",
    "steel",
    "steel gas stove",
    "gas stove",
    "steel stove",
    "soap",
    "speaker",
    "brand",
    "fridge",
    "burner",
    "roku",
    "netflix",
    "body wash",
    "cable",
    "freezer",
    "induction stove",
    "toaster",
    "apple tv",
    "pool",
    "fire tv",
    "chromecast",
    "disney+",
    "speakers",
    "plate",
    "premium cable",
    "kitchen",
    "gas",
    "ice maker",
    "water",
    "head",
    "air fryer",
    "steel induction stove",
    "door",
    "ice maker refrigerator",
    "brand conditioner",
    "bath",
    "parking garage",
    "cooktop",
    "foods",
    "range",
    "oil",
    "alexa",
    "body soap body soap",
    "moisture",
    "brand body soap",
    "steel refrigerator",
    "tea",
    "door refrigerator",
    "speaker sound system",
    "parking",
    "burners",
    "burner stove",
    "bar soap",
    "brands conditioner",
    "console",
    "radio",
    "bar soap body soap",
    "brands body soap",
    "sound bar",
    "toaster oven",
    "ice",
    "dove body soap",
    "bose",
    "shower",
    "brand shampoo",
    "skin",
    "oils",
    "living room",
    "brands shampoo",
    "chair",
    "hair conditioner",
    "garage",
    "plant",
    "parking lot",
    "closet",
    "refrigerator refrigerator",
    "driveway parking",
    "bottle",
    "water refrigerator",
    "tub",
    "soaps",
    "gas range",
    "burner gas stove",
    "arrival body soap",
    "arrival conditioner",
    "microwave",
    "skin body soap",
    "dispenser",
    "gas oven",
    "gel body soap",
    "clothing storage",
    "line",
    "hair types",
    "arrival shampoo",
    "space",
    "record player",
    "hand soap",
    "tea tree conditioner",
    "bbq grill",
    "ovens",
    "alexa sound system",
    "tv sound system",
    "burner induction stove",
    "side refrigerator",
    "speakers sound system",
    "oil shampoo",
    "convection oven",
    "player sound system",
    "sound bar sound system",
    "toiletries",
    "carport",
    "island soap",
    "burner cooktop",
    "griddle",
    "echo dot",
    "planet conditioner",
    "books",
    "water dispenser refrigerator",
    "table",
    "starter",
    "sugar",
    "refrigerators",
    "pots",
    "oil conditioner",
    "travel size shampoo",
    "countertop",
    "water dispenser",
    "toys",
    "spring body soap",
    "dove conditioner",
    "butter",
    "tea conditioner",
    "valet parking",
    "tea tree shampoo",
    "stovetop",
    "soap bar body soap",
    "planet shampoo",
    "phone",
    "induction cooktop",
    "washer",
    "room refrigerator",
    "onsite restaurant",
    "spa",
    "plates",
    "bar body soap",
    "pans",
    "soap shampoo",
    "gas burners",
    "amazon",
    "air",
    "ice dispenser refrigerator",
    "fuel",
    "microwave oven",
    "tea tree body soap",
    "dresser",
    "wardrobe",
    "coffee maker",
    "aloe",
    "tea body soap",
    "gym",
    "icemaker",
    "hair shampoo",
    "moisture conditioner",
    "coconut conditioner",
    "bose sound system",
    "fragrances",
    "ingredients",
    "backyard",
    "subwoofer sound system",
    "soundbar",
    "shower shampoo",
    "soaps body soap",
    "retro refrigerator",
    "subwoofer",
    "counter",
    "dial body soap",
    "dove body wash",
    "oils body soap",
    "travel size body soap",
    "shampoos",
    "tea shampoo",
    "shoulders conditioner",
    "point",
    "allergenic",
    "bar sound system",
    "method",
    "name brand",
    "salon",
    "pert",
    "sample size",
    "ski",
    "counter refrigerator",
    "bedroom",
    "pack",
    "receiver",
    "coconut milk",
    "aloe vera conditioner",
    "studio",
    "assortment",
    "tooth speaker",
    "body wash body soap",
    "wood",
    "wall",
    "ivory",
    "nature",
    "shower conditioner",
    "sound sound system",
    "brand refrigerator",
    "collection",
    "cusimax",
    "travel size conditioner",
    "store",
    "induction cooktop induction stove",
    "castile",
    "door refrigerator refrigerator",
    "others body soap",
    "botanicals shampoo",
    "plate stove",
    "dove shampoo",
    "exercise equipment",
    "farm",
    "formula",
    "size fridge refrigerator",
    "oster",
    "switch",
    "garnier",
    "glass top",
    "spice",
    "none",
    "butter body soap",
    "pool toys",
    "food",
    "plenty",
    "saltwater",
    "stove top",
    "selection",
    "phthalates",
    "plate induction stove",
    "burner cook",
    "cooktop induction stove",
    "lavender conditioner",
    "control",
    "apartment size",
    "grill",
    "variety body soap",
    "anker",
    "moisture shampoo",
    "lavender body soap",
    "apple music",
    "bose speaker",
    "hair types shampoo",
    "echo dot sound system",
    "apple",
    "arm",
    "patio",
    "shower gel",
    "bar soaps body soap",
    "body body soap",
    "view",
    "beach access",
    "planet body soap",
    "bed",
    "bed head",
    "air conditioner",
    "soap bars",
    "cds",
    "essentials conditioner",
    "induction burner",
    "changes",
    "crib",
    "cucumber",
    "moisture body soap",
    "shower gel body soap",
    "grapefruit",
    "ecosciences",
    "night",
    "drawer",
    "frigidaire refrigerator",
    "pizza",
    "cooking",
    "frigidaire gallery",
    "size stove",
    "fryer",
    "icemaker refrigerator",
    "gas cooktop",
    "% vegan cruelty",
    "shoulder",
    "showers",
    "housekeeping",
    "fireplace",
    "insignia",
    "stereo",
    "aide",
    "member",
    "meyers",
    "desert",
    "okeefe",
    "travel crib",
    "waste",
    "self care products",
    "amount",
    "sheamoisture",
    "varies",
    "traders",
    "foot refrigerator",
    "burner stovetop",
    "range stove",
    "home theater",
    "airfryer",
    "inch",
    "amenities body soap",
    "amenities conditioner",
    "coconut milk conditioner",
    "mint",
    "care shampoo",
    "hammer",
    "caress",
    "animal",
    "axe",
    "hotel body soap",
    "bodywash body soap",
]
