# Specify the database path
DATABASE_PATH = "data/listings.sqlite"

# Specify the cities list
CITIES = [
    "All Cities",
    "Asheville",
    "Austin",
    "Bozeman",
    "Broward County",
    "Cambridge",
    "Chicago",
    "Clark County NV",
    "Columbus",
    "Dallas",
    "Denver",
    "Fort Worth",
    "Hawaii",
    "Jersey City",
    "Los Angeles",
    "Nashville",
    "New Orleans",
    "New York City",
    "Newark",
    "Oakland",
    "Pacific Grove",
    "Portland",
    "Rhode Island",
    "Salem",
    "San Diego",
    "San Francisco",
    "San Mateo County",
    "Santa Clara County",
    "Santa Cruz County",
    "Seattle",
    "Twin Cities MSA",
    "Washington DC",
]

# Specify the chunk size for updating active quarter columns of ListingsCore
CHUNK_SIZE = 1000

AIRBNB_COLORS = {
    "main": "#FF5A5F",  # Rausch
    "green": "#00A699",  # Babu
    "orange": "#FC642D",  # Arches
    "darkgrey": "#484848",  # Hof
    "lightgrey": "#767676",  # Foggy
}

BENS_COLORS = {
    "nature-green": "#236F21",
    "tiffany-blue": "#83C5BE",
    "alice-blue": "#EDF6F9",
    "pale-dogwood": "#FFDDD2",
    "charcoal": "#2E5266",
}

# Mapping official Airbnb categories
AMENITY_CATEGORIES = {
    "Popular": [
        "Essentials",
        "Air conditioning",
        "Cleaning products",
        "Cooking basics",
        "Dedicated workspace",
        "Dishes and silverware",
        "Dryer",
        "Hair dryer",
        "Heating",
        "Hot tub",
        "Kitchen",
        "Pool",
        "TV",
        "Washer",
        "Wifi",
    ],
    "Bathroom": [
        "Bathtub",
        "Bidet",
        "Body soap",
        "Cleaning products",
        "Conditioner",
        "Hair dryer",
        "Hot water",
        "Outdoor shower",
        "Shampoo",
        "Shower gel",
    ],
    "Bedroom and laundry": [
        "Essentials",
        "Bed linens",
        "Clothing storage",
        "Dryer",
        "Drying rack for clothing",
        "Extra pillows and blankets",
        "Hangers",
        "Iron",
        "Mosquito net",
        "Room-darkening shades",
        "Safe",
        "Washer",
    ],
    "Entertainment": [
        "Arcade games",
        "Batting cage",
        "Books and reading material",
        "Bowling alley",
        "Climbing wall",
        "Ethernet connection",
        "Exercise equipment",
        "Game console",
        "Laser tag",
        "Life size games",
        "Mini golf",
        "Movie theater",
        "Piano",
        "Ping pong table",
        "Pool table",
        "Record player",
        "Skate ramp",
        "Sound system",
        "Theme room",
        "TV",
    ],
    "Family": [
        "Baby bath",
        "Baby monitor",
        "Children’s bikes",
        "Children's playroom",
        "Baby safety gates",
        "Babysitter recommendations",
        "Board games",
        "Changing table",
        "Children’s books and toys",
        "Children’s dinnerware",
        "Crib",
        "Fireplace guards",
        "High chair",
        "Outdoor playground",
        "Outlet covers",
        "Pack ’n play/Travel crib",
        "Table corner guards",
        "Window guards",
    ],
    "Heating and cooling": [
        "Air conditioning",
        "Ceiling fan",
        "Heating",
        "Indoor fireplace",
        "Portable fans",
    ],
    "Home safety": [
        "Carbon monoxide alarm",
        "Fire extinguisher",
        "First aid kit",
        "Smoke alarm",
    ],
    "Internet and office": ["Dedicated workspace", "Pocket wifi", "Wifi"],
    "Kitchen and dining": [
        "Barbecue utensils",
        "Bread maker",
        "Blender",
        "Coffee",
        "Coffee maker",
        "Cooking basics",
        "Dining table",
        "Dishes and silverware",
        "Dishwasher",
        "Freezer",
        "Hot water kettle",
    ],
    "Kitchen": [
        "Kitchenette",
        "Microwave",
        "Mini fridge",
        "Oven",
        "Refrigerator",
        "Rice maker",
        "Stove",
        "Toaster",
        "Trash compactor",
        "Wine glasses",
    ],
    "Location features": [
        "Beach access",
        "Lake access",
        "Laundromat nearby",
        "Private entrance",
        "Resort access",
        "Ski-in/Ski-out",
        "Waterfront",
    ],
    "Outdoor": [
        "Backyard",
        "BBQ grill",
        "Beach essentials",
        "Bikes",
        "Boat slip",
        "Fire pit",
        "Hammock",
        "Kayak",
        "Outdoor dining area",
        "Outdoor furniture",
        "Outdoor kitchen",
        "Patio or balcony",
        "Sun loungers",
    ],
    "Parking and facilities": [
        "Elevator",
        "EV charger",
        "Free parking on premises",
        "Hockey rink",
        "Free street parking",
        "Gym",
        "Hot tub",
        "Public or shared",
        "Paid parking off premises",
        "Paid parking on premises",
        "Pool",
        "Private living room",
        "Sauna",
        "Single level home",
    ],
    "Services": [
        "Breakfast",
        "Cleaning available during stay",
        "Long term stays allowed",
        "Luggage dropoff allowed",
    ],
}


# Set the types of columns for reading from CSV using pandas
COLUMN_IMPORT_TYPES = {
    "id": "int64",
    "listing_url": "str",
    "scrape_id": "float32",
    "last_scraped": "str",
    "scrape_name": "str",
    "name": "str",
    "description": "str",
    "picture_url": "str",
    "host_id": "float32",
    "host_url": "str",
    "host_name": "str",
    "host_since": "str",
    "host_location": "str",
    "host_about": "str",
    "host_response_time": "str",
    "host_response_rate": "str",
    "host_acceptance_rate": "str",
    "host_is_superhost": "str",
    "host_thumbnail_url": "str",
    "host_picture_url": "str",
    "host_neighbourhood": "str",
    "host_listings_count": "float32",
    "host_total_listings_count": "float32",
    "host_verifications": "str",
    "host_has_profile_pic": "str",
    "host_identity_verified": "str",
    "neighbourhood": "str",
    "neighbourhood_cleansed": "str",
    "latitude": "float32",
    "longitude": "float32",
    "property_type": "str",
    "room_type": "str",
    "accommodates": "float32",
    "bathrooms": "float32",
    "bathroom_text": "str",
    "bedrooms": "float32",
    "amenities": "str",
    "price": "str",
    "minimum_nights": "float32",
    "maximum_nights": "float32",
    "minimum_minimum_nights": "float32",
    "maximum_minimum_nights": "float32",
    "minimum_maximum_nights": "float32",
    "maximum_maximum_nights": "float32",
    "minimum_nights_avg_ntm": "float32",
    "maximum_nights_avg_ntm": "float32",
    "has_availability": "str",
    "availability_30": "float32",
    "availability_60": "float32",
    "availability_90": "float32",
    "availability_365": "float32",
    "calendar_last_scraped": "str",
    "number_of_reviews": "float32",
    "number_of_reviews_ltm": "float32",
    "first_review": "str",
    "last_review": "str",
    "review_scores_rating": "float64",
    "review_scores_accuracy": "float64",
    "review_scores_cleanliness": "float64",
    "review_scores_checkin": "float64",
    "review_scores_communication": "float64",
    "review_scores_location": "float64",
    "review_scores_value": "float64",
    "license": "str",
    "instant_bookable": "str",
    "reviews_per_month": "float32",
    "calculated_host_listings_count": "float32",
    "calculated_host_listings_count_entire_homes": "float32",
    "calculated_host_listings_count_private_rooms": "float32",
    "calculated_host_listings_count_shared_rooms": "float32",
}

# Specify the columns that need to be rounded as part of the review scores table
REVIEW_SCORES_COLUMNS = [
    "review_scores_rating",
    "review_scores_accuracy",
    "review_scores_cleanliness",
    "review_scores_checkin",
    "review_scores_communication",
    "review_scores_location",
    "review_scores_value",
]
